using System;
using System.Collections.Generic;
using Redemption.NPCs.Bosses.SeedOfInfection;
using Redemption.NPCs.Bosses.TheKeeper;
using Redemption.NPCs.Bosses.Warden;
using Redemption.NPCs.ChickenInv;
using Redemption.NPCs.Critters;
using Redemption.NPCs.Friendly;
using Redemption.NPCs.HM;
using Redemption.NPCs.Lab;
using Redemption.NPCs.Minibosses;
using Redemption.NPCs.Minibosses.SkullDigger;
using Redemption.NPCs.PostML;
using Redemption.NPCs.PreHM;
using Redemption.NPCs.Soulless;
using Redemption.NPCs.Wasteland;
using Terraria.ModLoader;

namespace Redemption
{
	public static class Lists
	{
		public static List<int> IsBunny = new List<int>
		{
			46,
			443,
			303,
			337,
			540
		};

		public static List<int> IsVanillaWeakSkeleton = new List<int>
		{
			77,
			-49,
			-51,
			-53,
			-47,
			449,
			450,
			451,
			452,
			566,
			567,
			481,
			201,
			-15,
			202,
			203,
			21,
			324,
			110,
			323,
			293,
			291,
			322,
			-48,
			-50,
			-52,
			-46,
			292,
			31,
			294,
			296,
			295,
			39,
			40,
			41,
			32,
			34,
			44,
			167,
			197,
			273,
			274,
			275,
			276,
			287,
			285,
			286,
			289,
			277,
			279,
			278,
			280,
			283,
			284,
			281,
			282,
			172,
			269,
			270,
			271,
			272
		};

		public static List<int> IsInfected = new List<int>
		{
			ModContent.NPCType<HazmatSkeleton>(),
			ModContent.NPCType<HazmatZombie>(),
			ModContent.NPCType<InfectedCaveBat>(),
			ModContent.NPCType<InfectedDemonEye>(),
			ModContent.NPCType<InfectedDiggerHead>(),
			ModContent.NPCType<InfectedDiggerBody>(),
			ModContent.NPCType<InfectedDiggerTail>(),
			ModContent.NPCType<InfectedGiantBat>(),
			ModContent.NPCType<InfectedGiantWormBody>(),
			ModContent.NPCType<InfectedGiantWormHead>(),
			ModContent.NPCType<InfectedGiantWormTail>(),
			ModContent.NPCType<InfectedGiantWormTail>(),
			ModContent.NPCType<InfectedZombie>(),
			ModContent.NPCType<SludgyBoi>(),
			ModContent.NPCType<XenoChomper>(),
			ModContent.NPCType<XenomiteGargantuan>(),
			ModContent.NPCType<XenomiteGolem>(),
			ModContent.NPCType<XenonRoller>(),
			ModContent.NPCType<RadiumDiggerBody>(),
			ModContent.NPCType<RadiumDiggerTail>(),
			ModContent.NPCType<RadiumDiggerHead>(),
			ModContent.NPCType<Blisterling>(),
			ModContent.NPCType<Blisterling2>(),
			ModContent.NPCType<InfectionHive>(),
			ModContent.NPCType<SludgyBlob>(),
			ModContent.NPCType<SludgyBoi2>(),
			ModContent.NPCType<Stage2Scientist>(),
			ModContent.NPCType<WalterInfected>(),
			ModContent.NPCType<XenoChomper2>(),
			ModContent.NPCType<XenomiteBeast>(),
			ModContent.NPCType<SpikyRadioactiveSlime>(),
			ModContent.NPCType<SneezyInfectedFlinx>(),
			ModContent.NPCType<RadiumRampager>(),
			ModContent.NPCType<RadiumDigger2Tail>(),
			ModContent.NPCType<RadiumDigger2Head>(),
			ModContent.NPCType<RadiumDigger2Body>(),
			ModContent.NPCType<RadioactiveSlime>(),
			ModContent.NPCType<NuclearSlime>(),
			ModContent.NPCType<InfectedSwarmer>(),
			ModContent.NPCType<InfectedSnowFlinx>(),
			ModContent.NPCType<InfectedChicken>(),
			ModContent.NPCType<GreenPigron>(),
			ModContent.NPCType<DecayedGhoul>(),
			ModContent.NPCType<BobTheBlob>(),
			ModContent.NPCType<Injector>(),
			ModContent.NPCType<BileBoomer>(),
			ModContent.NPCType<Injector>(),
			ModContent.NPCType<IrradiatedSpear>(),
			ModContent.NPCType<VirusJelly>(),
			ModContent.NPCType<Superbug>(),
			ModContent.NPCType<BloatedFaceMonster>(),
			ModContent.NPCType<BloatedGoldfish>(),
			ModContent.NPCType<IrradiatedWorldFeederTail>(),
			ModContent.NPCType<IrradiatedWorldFeederHead>(),
			ModContent.NPCType<IrradiatedWorldFeederBody>(),
			ModContent.NPCType<NerveParasite>(),
			ModContent.NPCType<RadioactiveSlimer>(),
			ModContent.NPCType<Xenoling>(),
			ModContent.NPCType<Superbug2>(),
			ModContent.NPCType<Blisterface2>(),
			ModContent.NPCType<IrradiatedBehemoth2>(),
			ModContent.NPCType<PZ2BodyCover>(),
			ModContent.NPCType<PZ2Fight>(),
			ModContent.NPCType<Stage3Scientist2>(),
			ModContent.NPCType<SeedGrowth>(),
			ModContent.NPCType<SoI>()
		};

		public static List<int> IsGhostly = new List<int>
		{
			84,
			179,
			83,
			533,
			288,
			182,
			316,
			140,
			82,
			253,
			330,
			ModContent.NPCType<Keeper>(),
			ModContent.NPCType<AAAA>(),
			ModContent.NPCType<DarkSoul>(),
			ModContent.NPCType<DarkSoul2>(),
			ModContent.NPCType<DarkSoul3>(),
			ModContent.NPCType<SkullDigger>(),
			ModContent.NPCType<WanderingSoul>(),
			ModContent.NPCType<IrradiatedSpear>(),
			ModContent.NPCType<SoullessAssassin>(),
			ModContent.NPCType<SoullessDueller>(),
			ModContent.NPCType<SoullessWanderer>(),
			ModContent.NPCType<BileBoomer>(),
			ModContent.NPCType<Shadebug>(),
			ModContent.NPCType<LaughingMaskBig>(),
			ModContent.NPCType<LaughingMaskMedium>(),
			ModContent.NPCType<LaughingMaskSmall>(),
			ModContent.NPCType<MansionWraith>(),
			ModContent.NPCType<MansionWraith2>(),
			ModContent.NPCType<WardenIdle>(),
			ModContent.NPCType<SoullessMarionette_Doll>(),
			ModContent.NPCType<SoullessMarionette_Cross>(),
			ModContent.NPCType<LaughingMaskSmall>(),
			ModContent.NPCType<LaughingMaskSmall>(),
			ModContent.NPCType<LaughingMaskSmall>(),
			ModContent.NPCType<LaughingMaskSmall>(),
			ModContent.NPCType<LaughingMaskSmall>()
		};

		public static List<int> IsDragonlike = new List<int>
		{
			551,
			558,
			559,
			560,
			170,
			180,
			171,
			370,
			ModContent.NPCType<GreenPigron>(),
			87,
			89,
			90,
			91,
			88,
			92,
			454,
			455,
			456,
			457,
			458,
			459
		};

		public static List<int> IsDemon = new List<int>
		{
			62,
			66,
			24,
			156
		};

		public static List<int> IsSoulless = new List<int>
		{
			ModContent.NPCType<SoullessAssassin>(),
			ModContent.NPCType<SoullessDueller>(),
			ModContent.NPCType<SoullessWanderer>(),
			ModContent.NPCType<ShadesoulNPC>(),
			ModContent.NPCType<SmallShadesoulNPC>(),
			ModContent.NPCType<TheSoulless2>(),
			ModContent.NPCType<TheSoulless>(),
			ModContent.NPCType<Shadebug>(),
			ModContent.NPCType<SoullessMarionette_Cross>(),
			ModContent.NPCType<SoullessMarionette_Doll>(),
			ModContent.NPCType<LaughingMaskSmall>(),
			ModContent.NPCType<LaughingMaskMedium>(),
			ModContent.NPCType<LaughingMaskBig>(),
			ModContent.NPCType<MansionWraith>(),
			ModContent.NPCType<MansionWraith2>(),
			ModContent.NPCType<WardenIdle>()
		};

		public static List<int> IsAnySkeleton = new List<int>
		{
			77,
			-49,
			-51,
			-53,
			-47,
			449,
			450,
			451,
			452,
			566,
			567,
			481,
			201,
			-15,
			202,
			203,
			21,
			324,
			110,
			323,
			293,
			291,
			322,
			-48,
			-50,
			-52,
			-46,
			292,
			31,
			294,
			296,
			295,
			39,
			40,
			41,
			32,
			34,
			44,
			167,
			197,
			273,
			274,
			275,
			276,
			287,
			285,
			286,
			289,
			277,
			279,
			278,
			280,
			283,
			284,
			281,
			282,
			172,
			269,
			270,
			271,
			272,
			68,
			35,
			36,
			ModContent.NPCType<BoneChicken>(),
			ModContent.NPCType<ChickmanChickromancer>(),
			ModContent.NPCType<BloodBoiledSkeleton>(),
			ModContent.NPCType<SkeletonAssassin2>(),
			ModContent.NPCType<SkeletonWanderer2>(),
			ModContent.NPCType<SkeletonWarden>(),
			ModContent.NPCType<Vepdor>(),
			ModContent.NPCType<BoneLeviathanBody>(),
			ModContent.NPCType<BoneLeviathanHead>(),
			ModContent.NPCType<BoneLeviathanTail>(),
			ModContent.NPCType<BoneSpider>(),
			ModContent.NPCType<CorpseWalkerPriest>(),
			ModContent.NPCType<DeathGardener>(),
			ModContent.NPCType<HazmatSkeleton>(),
			ModContent.NPCType<SkeleDruid>(),
			ModContent.NPCType<Skelemies>(),
			ModContent.NPCType<Skelemies2>(),
			ModContent.NPCType<SkeletonAssassin>(),
			ModContent.NPCType<SkeletonDueller>(),
			ModContent.NPCType<SkeletonMinion>(),
			ModContent.NPCType<SkeletonNoble>(),
			ModContent.NPCType<SkeletonNobleArmoured>(),
			ModContent.NPCType<SkeletonNobleArmoured2>(),
			ModContent.NPCType<SkeletonNobleArmoured3>(),
			ModContent.NPCType<SkeletonWanderer>()
		};
	}
}
